routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

use App\Http\Controllers\ClienteController;
use App\Http\Controllers\CompraController;
use App\Http\Controllers\ModeloController;
use App\Http\Controllers\ProdutoController;
use App\Http\Controllers\RastreamentoController;
use App\Http\Controllers\RemessaController;
use App\Http\Controllers\ServicoController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\VendedorController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Pagina Inicial
Route::get('/', function () {
    return view('landing');
});

Route::get('/dashboard', function () {
    if(Auth::user()->servico == null){
        return redirect()->route('servico.create');
    }else{
        return view('dashboard');
    }
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::post('/modelo/process', "App\Http\Controllers\ModeloController@process")->name('modelo.process')->middleware(['auth']);

Route::resource('cliente', ClienteController::class)->middleware(['auth']); //Rotas De Cliente
Route::resource('compra', CompraController::class)->middleware(['auth']); //Rotas De Compra
Route::resource('modelo', ModeloController::class)->middleware(['auth']); //Rotas De Compra
Route::resource('produto', ProdutoController::class)->middleware(['auth']); //Rotas De Produto
Route::resource('rastreamento', RastreamentoController::class)->middleware(['auth']); //Rotas De Rastreamento
Route::resource('remessa', RemessaController::class)->middleware(['auth']); //Rotas De Remessaa
Route::resource('servico', ServicoController::class)->middleware(['auth']); //Rotas De Servico
Route::resource('users', UserController::class)->middleware(['auth']); //Rotas De User
Route::resource('vendedor',VendedorController::class)->middleware(['auth']); //Rotas De Vendedor

//Rota De Geracao De Modelos

//Rotas De Datatable
Route::prefix('/api')->group(function (){ //// endereco/api
    Route::prefix('/datatables')->group(function () { //// endereco/api/datatables
        Route::get('/cliente', "App\Http\Controllers\ClienteController@datatableProvider")->name('datatables.cliente')->middleware(['auth']); //Cliente
        Route::get('/compra', "App\Http\Controllers\CompraController@datatableProvider")->name('datatables.compra')->middleware(['auth']); //Compra
        Route::get('/modelo', "App\Http\Controllers\ModeloController@datatableProvider")->name('datatables.modelo')->middleware(['auth']); //Modelo
        Route::get('/produto', "App\Http\Controllers\ProdutoController@datatableProvider")->name('datatables.produto')->middleware(['auth']); //Produto
        Route::get('/rastreamento', "App\Http\Controllers\RastreamentoController@datatableProvider")->name('datatables.rastreamento')->middleware(['auth']); //Rastreamento
        Route::get('/remessa', "App\Http\Controllers\RemessaController@datatableProvider")->name('datatables.remessa')->middleware(['auth']); //Remessa
        Route::get('/vendedor', "App\Http\Controllers\VendedorController@datatableProvider")->name('datatables.vendedor')->middleware(['auth']); //Vendedor
    });
});

//Rota De Sobre
Route::get('/sobre', function () {
    return view('outros.sobre');
})->name('sobre')->middleware(['auth']);

Route::get('/instrucoes', function () {
    return view('outros.instrucoes');
})->name('instrucoes')->middleware(['auth']);














//Pagina Testes Editor
Route::get('/editor', function () {
    return view('editor');
})->name("editor");

app/Models/Vendedor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Vendedor extends Model
{
    use HasFactory;

    protected $table = 'vendedor';

    public function servico(){
        return $this->belongsTo('App\Models\Servico');
    }

    public function produto(){
        return $this->hasMany('App\Models\Produto','vendedor_id','id');
    }

}

app/Http/Controllers/VendedorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\Servico;
use App\Models\Vendedor;

class VendedorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $servico = Auth::user()->servico;
        $vendedores = $servico->vendedor;
        return view('vendedor.index',["servico"=>$servico,"vendedores"=>$vendedores]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $servico = Auth::user()->servico;
        return view('vendedor.create',['servico'=>$servico]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(
            [   
                "nome"=>['required','max:255','string'],
                "telefone"=>['nullable','max:255'],
                "email"=>['required','max:255','email'],
                "pais"=>['required','max:255','string'],
                "servicoId"=>['required']
            ]
        );
        $vendedor = new Vendedor();
        $vendedor->servico_id = $request->input('servicoId');
        if($request->input('telefone') != null){
            $vendedor->telefone = $request->input('telefone');
        }
        $vendedor->pais = $request->input('pais');
        $vendedor->email = $request->input('email');
        $vendedor->nome = $request->input('nome');
        $vendedor->save();
        $request->session()->flash('mensagemSucessoAdicionar', "Vendedor Adicionado Com Sucesso");
        return redirect()->route("vendedor.index");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $vendedor = Vendedor::find($id);
        $servico = $vendedor->servico;
        if($vendedor == null){
            return redirect()->back;
        }else{
            return view('vendedor.edit',['vendedor'=>$vendedor,'servico'=>$servico]);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $vendedor = Vendedor::find($id);
        if($vendedor == null){
            return redirect()->back();
        }else{
            $request->validate(
                [   
                    "nome"=>['required','max:255','string'],
                    "telefone"=>['nullable','max:255'],
                    "email"=>['required','max:255','email'],
                    "pais"=>['required','max:255','string'],
                    "servicoId"=>['required']
                ]
            );
            if($request->input('telefone') != null){
                $vendedor->telefone = $request->input('telefone');
            }
            $vendedor->pais = $request->input('pais');
            $vendedor->email = $request->input('email');
            $vendedor->nome = $request->input('nome');
            $vendedor->save();
            $request->session()->flash('mensagemSucessoAtualizar', "Vendedor Atualizado Com Sucesso");
            return redirect()->route("vendedor.index");
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $vendedor = Vendedor::find($id);
        if($vendedor == null){
            return redirect()->back();
        }else{
            $nomeVendedor = $vendedor->nome."";
            $vendedor->delete();
            $request->session()->flash('mensagemSucessoApagar', "Vendedor \"".$nomeVendedor."\" apagado com sucesso");
            return redirect()->route("vendedor.index");
        }
    }

    public function datatableProvider(){
        $servico = Auth::user()->servico;
        $vendedores = $servico->vendedor;
        return response()->json($vendedores);
    }
}

resources/views/vendedor/create.blade.php
@extends('layouts.master')
@php
$menuSelectPath = ['categ' => 'registros', 'submenu' => 'vendedor'];
@endphp
@section('headerLinks')
    <link rel="stylesheet" href="{{ asset('css/flareeditor/forminput.css') }}">
@endsection
@section('pageTitle')
    Adicionar Vendedor
@endsection
@section('bodyTitle')
    Adicionar Vendedor
@endsection
@section('bodyContent')
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-10">
                    <form method="POST" action="{{ route('vendedor.store') }}">
                        @csrf
                        <div class="form-group">
                            <label for="nome">Nome <code>*</code><span></label>
                            <input type="text" class="form-control flareeditor-input-orange" id="nome"
                                placeholder="Nome do Vendedor" name="nome">
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="telefone">Telefone</label>
                                    <input type="text" class="form-control flareeditor-input-orange" id="telefone"
                                        placeholder="Telefone Do Vendedor" name="telefone">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="pais">País <code>*</code></label>
                                    <input type="text" class="form-control flareeditor-input-orange" id="pais"
                                        placeholder="País do Vendedor" name="pais">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="email">Email <code>*</code></label>
                            <input type="email" class="form-control flareeditor-input-orange" id="email"
                                placeholder="Email Do Vendedor" name="email">
                        </div>
                        <input type="hidden" name="servicoId" value="{{ $servico->id }}">
                        <!-- /.card-body -->
                        <span><code>*</code> Campos Obrigatórios</span>
                        <br><br>
                        <button type="submit" class="btn btn-primary">Adicionar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/vendedor/edit.blade.php
@extends('layouts.master')
@php
$menuSelectPath = ['categ' => 'registros', 'submenu' => 'vendedor'];
@endphp
@section('headerLinks')
    <link rel="stylesheet" href="{{ asset('css/flareeditor/forminput.css') }}">
@endsection
@section('pageTitle')
    Atualizar Dados de Vendedor
@endsection
@section('bodyTitle')
    Atualizar Dados de Vendedor
@endsection
@section('bodyContent')
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-10">
                    <form method="POST" action="{{ route('vendedor.update',$vendedor->id) }}">
                        @method('put')
                        @csrf
                        <div class="form-group">
                            <label for="nome">Nome <code>*</code><span></label>
                            <input type="text" class="form-control flareeditor-input-orange" id="nome"
                                placeholder="Nome do Vendedor" name="nome" value="{{ $vendedor->nome }}">
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="telefone">Telefone</label>
                                    <input type="text" class="form-control flareeditor-input-orange" id="telefone"
                                        placeholder="Telefone Do Vendedor" name="telefone" value="@if ($vendedor->telefone != null){{ $vendedor->telefone }}@endif">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="pais">País <code>*</code></label>
                                    <input type="text" class="form-control flareeditor-input-orange" id="pais"
                                        placeholder="País do Vendedor" name="pais" value="{{ $vendedor->pais }}">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="email">Email <code>*</code></label>
                            <input type="email" class="form-control flareeditor-input-orange" id="email"
                                placeholder="Email Do Vendedor" name="email" value="{{ $vendedor->email }}">
                        </div>
                        <input type="hidden" name="servicoId" value="{{ $servico->id }}">
                        <!-- /.card-body -->
                        <span><code>*</code> Campos Obrigatórios</span>
                        <br><br>
                        <button type="submit" class="btn btn-primary">Atualizar Dados</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/vendedor/index.blade.php
@extends('layouts.master')
@php
$usePreloader = true;
$menuSelectPath = ['categ' => 'registros', 'submenu' => 'vendedor'];
@endphp
@section('headerLinks')
    <link rel="stylesheet" href="{{ asset('datatables/datatables.min.css') }}">
    <link rel="stylesheet" href="{{ asset('datatables/dt/css/dataTables.bootstrap4.min.css') }}">
@endsection
@section('pageTitle')
    Vendedores
@endsection
@section('bodyTitle')
    Visualizar Vendedores
@endsection
@section('bodyContent')
    <a role="button" class="btn btn-primary m-2" href="{{ route('vendedor.create') }}">Cadastrar Novo Vendedor</a><br>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table id="tableVendedor" class="table table-bordered">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">Nome</th>
                                <th scope="col">Email</th>
                                <th scope="col">País</th>
                                <th scope="col">Opções</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    @foreach ($vendedores as $vendedor)
        <form action="{{ route('vendedor.destroy', $vendedor->id) }}" method="POST">
            @method("delete")
            @csrf
            <div class="modal fade" id="modalDelete{{ $vendedor->id }}" tabindex="-1" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Apagar Vendedor</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>Deseja apagar o vendedor <b>{{ $vendedor->nome }}</b>? </p>
                            <p></p>
                            <p><span class="text-danger">Esta ação nao pode ser desfeita</span> </p>
                        </div>
                        <div class="modal-footer justify-content-right">
                            <button type="button" class="btn btn-primary" data-dismiss="modal">Não</button>
                            <button type="submit" class="btn btn-danger">Sim</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    @endforeach

@endsection

@section('footerLinks')
    <script src="{{ asset('datatables/datatables.min.js') }}"></script>
    <script src="{{ asset('datatables/dt/js/dataTables.bootstrap4.min.js') }}"></script>
    <script type="text/javascript">
        function mostrarModal(idModal) {
            $("#modalDelete" + idModal).modal("show");
        }
    </script>
    @php
    $subtitulo = "";
    if (session()->exists('mensagemSucessoApagar')) {
        $mensagemSucesso = session()->get('mensagemSucessoApagar');
        $subtitulo = "Apagar Vendedor";
        session()->forget('mensagemSucessoApagar');
    } elseif (session()->exists('mensagemSucessoAdicionar')) {
        $mensagemSucesso = session()->get('mensagemSucessoAdicionar');
        $subtitulo = "Adicionar Vendedor";
        session()->forget('mensagemSucessoAdicionar');
    } elseif (session()->exists('mensagemSucessoAtualizar')) {
        $mensagemSucesso = session()->get('mensagemSucessoAtualizar');
        $subtitulo = "Atualizar Vendedor";
        session()->forget('mensagemSucessoAtualizar');
    } else {
        $mensagemSucesso = null;
    }
    @endphp

    @if ($mensagemSucesso != null)
        <script type="text/javascript">
            $(document).ready(function() {
                $(document).Toasts('create', {
                    class: 'bg-success',
                    title: 'Sucesso',
                    subtitle: '{{ $subtitulo }}',
                    body: '<h6>{{ $mensagemSucesso }}</h6>'
                    {{ $mensagemSucesso = null }}
                })
            });
        </script>
    @endif


    <script>
        var id = null;
        $('#tableVendedor').DataTable({
            "language": {
                "url": "{{ asset('datatables/pt_br.json') }}"
            },
            "order": [
                [0, "asc"]
            ],
            pageLength: 5,
            "lengthMenu": [
                [5, 10, 25, 50],
                [5, 10, 25, 50]
            ],
            "ajax": {
                "url": '{{ route('datatables.vendedor') }}',
                "dataSrc": "",
                "type": "GET"
            },
            "columns": [{
                    data: 'nome',
                    name: 'Nome'
                },
                {
                    data: 'email',
                    name: 'Email'
                },
                {
                    data: 'pais',
                    name: 'País'
                },
                {
                    data: 'id',
                    name: "Opções",
                    render: function(id, type, row) {
                        var html = '<div class="row">'
                        html += '    <div class="col-md-6">'
                        html += '        <p>'
                        html += '            <a href="/vendedor/' + id +
                            '/edit" class="btn btn-primary btn-block">'
                        html += '                Editar'
                        html += '            </a>'
                        html += '        </p>'
                        html += '    </div>'
                        html += '    <div class="col-md-6">'
                        html += '        <p>'
                        html += '            <button type="button" onclick="mostrarModal(' + id +
                            ')" class="btn btn-danger btn-block">'
                        html += '                Apagar'
                        html += '            </button>'
                        html += '        </p>'
                        html += '    </div>'
                        html += '</div">'
                        return html;
                    }
                }
            ]
        });
    </script>
@endsection