routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

use App\Http\Controllers\ClienteController;
use App\Http\Controllers\CompraController;
use App\Http\Controllers\ModeloController;
use App\Http\Controllers\ProdutoController;
use App\Http\Controllers\RastreamentoController;
use App\Http\Controllers\RemessaController;
use App\Http\Controllers\ServicoController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\VendedorController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Pagina Inicial
Route::get('/', function () {
    return view('landing');
});

Route::get('/dashboard', function () {
    if(Auth::user()->servico == null){
        return redirect()->route('servico.create');
    }else{
        return view('dashboard');
    }
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::post('/modelo/process', "App\Http\Controllers\ModeloController@process")->name('modelo.process')->middleware(['auth']);

Route::resource('cliente', ClienteController::class)->middleware(['auth']); //Rotas De Cliente
Route::resource('compra', CompraController::class)->middleware(['auth']); //Rotas De Compra
Route::resource('modelo', ModeloController::class)->middleware(['auth']); //Rotas De Compra
Route::resource('produto', ProdutoController::class)->middleware(['auth']); //Rotas De Produto
Route::resource('rastreamento', RastreamentoController::class)->middleware(['auth']); //Rotas De Rastreamento
Route::resource('remessa', RemessaController::class)->middleware(['auth']); //Rotas De Remessaa
Route::resource('servico', ServicoController::class)->middleware(['auth']); //Rotas De Servico
Route::resource('users', UserController::class)->middleware(['auth']); //Rotas De User
Route::resource('vendedor',VendedorController::class)->middleware(['auth']); //Rotas De Vendedor

//Rota De Geracao De Modelos

//Rotas De Datatable
Route::prefix('/api')->group(function (){ //// endereco/api
    Route::prefix('/datatables')->group(function () { //// endereco/api/datatables
        Route::get('/cliente', "App\Http\Controllers\ClienteController@datatableProvider")->name('datatables.cliente')->middleware(['auth']); //Cliente
        Route::get('/compra', "App\Http\Controllers\CompraController@datatableProvider")->name('datatables.compra')->middleware(['auth']); //Compra
        Route::get('/modelo', "App\Http\Controllers\ModeloController@datatableProvider")->name('datatables.modelo')->middleware(['auth']); //Modelo
        Route::get('/produto', "App\Http\Controllers\ProdutoController@datatableProvider")->name('datatables.produto')->middleware(['auth']); //Produto
        Route::get('/rastreamento', "App\Http\Controllers\RastreamentoController@datatableProvider")->name('datatables.rastreamento')->middleware(['auth']); //Rastreamento
        Route::get('/remessa', "App\Http\Controllers\RemessaController@datatableProvider")->name('datatables.remessa')->middleware(['auth']); //Remessa
        Route::get('/vendedor', "App\Http\Controllers\VendedorController@datatableProvider")->name('datatables.vendedor')->middleware(['auth']); //Vendedor
    });
});

//Rota De Sobre
Route::get('/sobre', function () {
    return view('outros.sobre');
})->name('sobre')->middleware(['auth']);

Route::get('/instrucoes', function () {
    return view('outros.instrucoes');
})->name('instrucoes')->middleware(['auth']);














//Pagina Testes Editor
Route::get('/editor', function () {
    return view('editor');
})->name("editor");

app/Models/Compra.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Compra extends Model
{
    use HasFactory;

    protected $table = 'compra';

    public function servico(){
        return  $this->belongsTo('App\Models\Servico');
    }

    public function cliente(){
        return  $this->belongsTo('App\Models\Cliente');
    }

    public function remessa(){
        return  $this->belongsTo('App\Models\Remessa');
    }

    public function produto(){
        return  $this->belongsTo('App\Models\Produto');
    }

}

app/Http/Controllers/CompraController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\Servico;
use App\Models\User;
use App\Models\Compra;
use App\Models\Cliente;
use App\Models\Rastreamento;
use App\Models\Remessa;
use App\Models\Vendedor;
use App\Models\Produto;


class CompraController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $servico = Auth::user()->servico;
        $compras = Compra::where('servico_id',$servico->id)->with(['servico','cliente','produto','produto.vendedor','remessa','remessa.rastreamento'])->get();
        return view('compra.index',["servico"=>$servico,"compras"=>$compras]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $servico = Auth::user()->servico;
        $remessas = Remessa::where('servico_id',$servico->id)->with(['rastreamento'])->get();
        $clientes = $servico->cliente;
        $produtos = Produto::where('servico_id',$servico->id)->with(['vendedor'])->get();
        return view("compra.create",["servico"=>$servico,"remessas"=>$remessas,"clientes"=>$clientes,"produtos"=>$produtos]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            "clienteId"=>['required','numeric'],
            "produtoId"=>['required','numeric'],
            "remessaId"=>['required','numeric'],
            "servicoId"=>['required','numeric'],
            "quantidade"=>['required','numeric']
        ]);
        $compra = new Compra();
        $compra->cliente_id = $request->input("clienteId");
        $compra->produto_id = $request->input("produtoId");
        $compra->remessa_id = $request->input("remessaId");
        $compra->servico_id = $request->input("servicoId");
        $compra->quantidade = $request->input("quantidade");
        $compra->save();
        $request->session()->flash('mensagemSucessoAdicionar', "Compra Adicionada Com Sucesso");
        return redirect()->route("compra.index");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $servico = Auth::user()->servico;
        $remessas = Remessa::where('servico_id',$servico->id)->with(['rastreamento'])->get();
        $clientes = $servico->cliente;
        $produtos = Produto::where('servico_id',$servico->id)->with(['vendedor'])->get();
        $compra = Compra::find($id);
        if($compra == null){
            return redirect()->back();
        }else{
            return view("compra.edit",["compra"=>$compra,"servico"=>$servico,"remessas"=>$remessas,"clientes"=>$clientes,"produtos"=>$produtos]);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $compra = Compra::find($id);
        if($compra == null){
            return redirect()->back();
        }else{
            $request->validate([
                "clienteId"=>['required','numeric'],
                "produtoId"=>['required','numeric'],
                "remessaId"=>['required','numeric'],
                "servicoId"=>['required','numeric'],
                "quantidade"=>['required','numeric']
            ]);
            $compra->cliente_id = $request->input("clienteId");
            $compra->produto_id = $request->input("produtoId");
            $compra->remessa_id = $request->input("remessaId");
            $compra->servico_id = $request->input("servicoId");
            $compra->quantidade = $request->input("quantidade");
            $compra->save();
            $request->session()->flash('mensagemSucessoAtualizar', "Compra Atualizada Com Sucesso");
            return redirect()->route("compra.index");
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request,$id)
    {
        $compra = Compra::find($id)::with(['produto'])->get();
        if($compra == null){
            return redirect()->back();
        }else{
            $compra = $compra[0];
            $compraDoQue = $compra->quantidade."x ".$compra->produto->descricao."";
            $compra->delete();
            $request->session()->flash('mensagemSucessoApagar', "Compra \"".$compraDoQue."\" apagada com sucesso");
            return redirect()->route("compra.index");
        }
    }

    public function datatableProvider(){
        $servico = Auth::user()->servico;
        $compras = Compra::where('servico_id',$servico->id)->with(['servico','cliente','produto','produto.vendedor','remessa','remessa.rastreamento'])->get();
        return response()->json($compras);
    }
}

resources/views/compra/create.blade.php
@extends('layouts.master')
@php
$menuSelectPath = ['categ' => 'registros', 'submenu' => 'compra'];
@endphp
@section('headerLinks')
    <link rel="stylesheet" href="{{ asset('css/flareeditor/forminput.css') }}">
@endsection
@section('pageTitle')
    Adicionar Compra
@endsection
@section('bodyTitle')
    Adicionar Compra
@endsection
@section('bodyContent')
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-10">
                    <form method="POST" action="{{ route('compra.store') }}">
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="clienteId">Cliente <code>*</code></label>
                                    <select class="form-control flareeditor-input-orange" id="clienteId" name="clienteId">
                                        @foreach ($clientes as $cliente)
                                            <option value="{{ $cliente->id }}">{{ $cliente->nome." ".$cliente->sobrenome }}</option>
                                        @endforeach
                                      </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="remessaId">Remessa <code>*</code></label>
                                    <select class="form-control flareeditor-input-orange" id="remessaId" name="remessaId">
                                        @foreach ($remessas as $remessa)
                                            <option value="{{ $remessa->id }}">{{ $remessa->codigoRastreamento."  (".$remessa->rastreamento->nomeEmpresa.")" }}</option>
                                        @endforeach
                                      </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="produtoId">Produto <code>*</code></label>
                                    <select class="form-control flareeditor-input-orange" id="produtoId" name="produtoId">
                                        @foreach ($produtos as $produto)
                                            <option value="{{ $produto->id }}">{{ $produto->descricao." (".$produto->vendedor->nome.")" }}</option>
                                        @endforeach
                                      </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="quantidade">Quantidade <code>*</code></label>
                                    <input type="number" class="form-control flareeditor-input-orange" id="quantidade"
                                        placeholder="Quantidade De Produtos" name="quantidade" min="1" value="1">
                                </div>
                            </div>
                        </div>
                        <input type="hidden" name="servicoId" value="{{ $servico->id }}">
                        <!-- /.card-body -->
                        <span><code>*</code> Campos Obrigatórios</span>
                        <br><br>
                        <button type="submit" class="btn btn-primary">Adicionar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/compra/edit.blade.php
@extends('layouts.master')
@php
$menuSelectPath = ['categ' => 'registros', 'submenu' => 'compra'];
@endphp
@section('headerLinks')
    <link rel="stylesheet" href="{{ asset('css/flareeditor/forminput.css') }}">
@endsection
@section('pageTitle')
    Atualizar Dados de Compra
@endsection
@section('bodyTitle')
    Atualizar Dados de Compra
@endsection
@section('bodyContent')
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-10">
                    <form method="POST" action="{{ route('compra.update',$compra->id) }}">
                        @method('put')
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="clienteId">Cliente <code>*</code></label>
                                    <select class="form-control flareeditor-input-orange" id="clienteId" name="clienteId">
                                        @foreach ($clientes as $cliente)
                                            <option value="{{ $cliente->id }}" @if($compra->cliente_id == $cliente->id) selected @endif>{{ $cliente->nome." ".$cliente->sobrenome }}</option>
                                        @endforeach
                                      </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="remessaId">Remessa <code>*</code></label>
                                    <select class="form-control flareeditor-input-orange" id="remessaId" name="remessaId">
                                        @foreach ($remessas as $remessa)
                                            <option value="{{ $remessa->id }}" @if($compra->remessa_id == $remessa->id) selected @endif>{{$remessa->codigoRastreamento."  (".$remessa->rastreamento->nomeEmpresa.")"}}</option>
                                        @endforeach
                                      </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="produtoId">Produto <code>*</code></label>
                                    <select class="form-control flareeditor-input-orange" id="produtoId" name="produtoId">
                                        @foreach ($produtos as $produto)
                                            <option value="{{ $produto->id }}" @if($compra->produto_id == $produto->id) selected @endif>{{ $produto->descricao." (".$produto->vendedor->nome.")" }}</option>
                                        @endforeach
                                      </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="quantidade">Quantidade <code>*</code></label>
                                    <input type="number" class="form-control flareeditor-input-orange" id="quantidade"
                                        placeholder="Quantidade De Produtos" name="quantidade" min="1" value="{{ $compra->quantidade }}">
                                </div>
                            </div>
                        </div>
                        <input type="hidden" name="servicoId" value="{{ $servico->id }}">
                        <!-- /.card-body -->
                        <span><code>*</code> Campos Obrigatórios</span>
                        <br><br>
                        <button type="submit" class="btn btn-primary">Atualizar Dados</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/compra/index.blade.php
@extends('layouts.master')
@php
$usePreloader = true;
$menuSelectPath = ['categ' => 'registros', 'submenu' => 'compra'];
@endphp
@section('headerLinks')
    <link rel="stylesheet" href="{{ asset('datatables/datatables.min.css') }}">
    <link rel="stylesheet" href="{{ asset('datatables/dt/css/dataTables.bootstrap4.min.css') }}">
@endsection
@section('pageTitle')
    Compras
@endsection
@section('bodyTitle')
    Visualizar Compras
@endsection
@section('bodyContent')
    <a role="button" class="btn btn-primary m-2" href="{{ route('compra.create') }}">Cadastrar Nova Compra</a><br>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table id="tableCompra" class="table table-bordered">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">Cliente</th>
                                <th scope="col">Produto</th>
                                <th scope="col">Remessa</th>
                                <th scope="col">Quantidade</th>
                                <th scope="col">Opções</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    @foreach ($compras as $compra)
        <form action="{{ route('compra.destroy', $compra->id) }}" method="POST">
            @method("delete")
            @csrf
            <div class="modal fade" id="modalDelete{{ $compra->id }}" tabindex="-1" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Apagar Compra</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>Deseja apagar a compra de <b>{{ $compra->quantidade }}x {{$compra->produto->descricao}}</b>? </p>
                            <p></p>
                            <p><span class="text-danger">Esta ação nao pode ser desfeita</span> </p>
                        </div>
                        <div class="modal-footer justify-content-right">
                            <button type="button" class="btn btn-primary" data-dismiss="modal">Não</button>
                            <button type="submit" class="btn btn-danger">Sim</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    @endforeach

@endsection

@section('footerLinks')
    <script src="{{ asset('datatables/datatables.min.js') }}"></script>
    <script src="{{ asset('datatables/dt/js/dataTables.bootstrap4.min.js') }}"></script>
    <script type="text/javascript">
        function mostrarModal(idModal) {
            $("#modalDelete" + idModal).modal("show");
        }
    </script>
    @php
    $subtitulo = "";
    if (session()->exists('mensagemSucessoApagar')) {
        $mensagemSucesso = session()->get('mensagemSucessoApagar');
        $subtitulo = "Apagar Compra";
        session()->forget('mensagemSucessoApagar');
    } elseif (session()->exists('mensagemSucessoAdicionar')) {
        $mensagemSucesso = session()->get('mensagemSucessoAdicionar');
        $subtitulo = "Adicionar Compra";
        session()->forget('mensagemSucessoAdicionar');
    } elseif (session()->exists('mensagemSucessoAtualizar')) {
        $mensagemSucesso = session()->get('mensagemSucessoAtualizar');
        $subtitulo = "Atualizar Compra";
        session()->forget('mensagemSucessoAtualizar');
    } else {
        $mensagemSucesso = null;
    }
    @endphp

    @if ($mensagemSucesso != null)
        <script type="text/javascript">
            $(document).ready(function() {
                $(document).Toasts('create', {
                    class: 'bg-success',
                    title: 'Sucesso',
                    subtitle: '{{ $subtitulo }}',
                    body: '<h6>{{ $mensagemSucesso }}</h6>'
                    {{ $mensagemSucesso = null }}
                })
            });
        </script>
    @endif


    <script>
        var id = null;
        $('#tableCompra').DataTable({
            "language": {
                "url": "{{ asset('datatables/pt_br.json') }}"
            },
            "order": [
                [0, "asc"]
            ],
            pageLength: 5,
            "lengthMenu": [
                [5, 10, 25, 50],
                [5, 10, 25, 50]
            ],
            "ajax": {
                "url": '{{ route('datatables.compra') }}',
                "dataSrc": "",
                "type": "GET"
            },
            "columns": [{
                    data: 'cliente',
                    name: 'Cliente',
                    render: function(cliente,type,row){
                        var nomeCompleto = cliente.nome+" "+cliente.sobrenome;
                        return nomeCompleto;
                    }
                },
                {
                    data: 'produto.descricao',
                    name: 'Empresa'
                },
                {
                    data: 'remessa.codigoRastreamento',
                    name: 'Remessa'
                },
                {
                    data: 'quantidade',
                    name: 'Quantidade'
                },
                {
                    data: 'id',
                    name: "Opções",
                    orderable: false,
                    render: function(id, type, row) {
                        var html = '<div class="row">'
                        html += '    <div class="col-md-6">'
                        html += '        <p>'
                        html += '            <a href="/compra/' + id +
                            '/edit" class="btn btn-primary btn-block">'
                        html += '                Editar'
                        html += '            </a>'
                        html += '        </p>'
                        html += '    </div>'
                        html += '    <div class="col-md-6">'
                        html += '        <p>'
                        html += '            <button type="button" onclick="mostrarModal(' + id +
                            ')" class="btn btn-danger btn-block">'
                        html += '                Apagar'
                        html += '            </button>'
                        html += '        </p>'
                        html += '    </div>'
                        html += '</div">'
                        return html;
                    }
                }
            ]
        });
    </script>
@endsection